# 1. 正しい部品を直接指定する
windows_mysql_path: &windows_mysql_path
  lib: C:\Ruby32-x64\bin\libmysql.dll

default: &default
  adapter: mysql2
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: ''
  host: localhost
  # variables:
  #   local_infile: true 

development:
  <<: *default
  database: furima_41972_development

test:
  <<: *default
  database: furima_41972_test

production:
  <<: *default
  database: furima_41972_production
  username: furima_41972
  password: ''