default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: ''
  host: localhost

development:
  <<: *default
  adapter: mysql2        # 開発環境は MySQL
  encoding: utf8mb4      # 開発環境は utf8mb4
  database: furima_41972_development

test:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: furima_41972_test

production:
  <<: *default
  adapter: postgresql    # 本番環境(Render)は PostgreSQL
  encoding: unicode      # 本番環境は unicode
  database: furima_41972_production
  username: furima_41972
  password: <%= ENV["FURIMA_41972_DATABASE_PASSWORD"] %>